name: murmur3
description: MurmurHash v3 for Dart & Flutter platforms. Supports array and stream data sources, on native and browser environments.
version: 2.0.0
repository: https://www.github.com/d-markey/murmur3

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
